<?php
/**
 * Static dataset describing the Legends of the Park flag football league.
 *
 * @package Legends_Of_The_Park
 */

return array(
    'season_highlights' => array(
        array(
            'label'       => 'Registered Teams',
            'value'       => '24',
            'description' => 'Across four competitive and community divisions.',
        ),
        array(
            'label'       => 'Weekly Matchups',
            'value'       => '12',
            'description' => 'Double-headers every Thursday and Saturday night.',
        ),
        array(
            'label'       => 'Certified Officials',
            'value'       => '18',
            'description' => 'NFHS & USA Flag accredited crew keeping play safe.',
        ),
        array(
            'label'       => 'Community Clinics',
            'value'       => '9',
            'description' => 'Skills labs, film rooms, and youth mentorship sessions.',
        ),
    ),
    'upcoming_games' => array(
        array(
            'date'      => 'July 12',
            'date_iso'  => '2024-07-12',
            'time'      => '7:00 PM',
            'matchup'   => 'Sunset Strikers vs. Neon Knights',
            'division'  => 'Pro-Am Division',
            'location'  => 'Starburst Park Stadium, Las Vegas',
            'storyline' => 'Two unbeaten squads collide in a showdown of hurry-up offenses and hybrid cover shells.',
            'cta'       => array(
                'label' => 'RSVP on Discord',
                'url'   => 'https://discord.gg/25bXKqSN',
            ),
        ),
        array(
            'date'      => 'July 13',
            'date_iso'  => '2024-07-13',
            'time'      => '6:30 PM',
            'matchup'   => 'Silver State Cyclones vs. Desert Vipers',
            'division'  => 'Open Division',
            'location'  => 'Heritage Gridiron Complex, Henderson',
            'storyline' => 'Cyclones lean on precision route trees while the Vipers unleash a bend-don’t-break defense.',
            'cta'       => array(
                'label' => 'Add to Calendar',
                'url'   => 'https://calendar.google.com/',
            ),
        ),
        array(
            'date'      => 'July 18',
            'date_iso'  => '2024-07-18',
            'time'      => '5:45 PM',
            'matchup'   => 'Wildflower Warriors vs. Mojave Mermaids',
            'division'  => 'Women’s Elevate Division',
            'location'  => 'Legends Practice Fields, North Las Vegas',
            'storyline' => 'League-leading defenses clash with championship seeding on the line.',
            'cta'       => array(
                'label' => 'Volunteer Chain Crew',
                'url'   => 'mailto:volunteer@legendsofthepark.com',
            ),
        ),
        array(
            'date'      => 'July 20',
            'date_iso'  => '2024-07-20',
            'time'      => '4:15 PM',
            'matchup'   => 'Future Flyers vs. Sparks Falcons',
            'division'  => 'Rising Stars Division',
            'location'  => 'Northern Lights Athletic Field, Sparks',
            'storyline' => 'Youth captains debut new motion sets coached by Legends alumni.',
            'cta'       => array(
                'label' => 'Youth RSVP Form',
                'url'   => 'https://legendsofthepark.com/forms/youth-rsvp',
            ),
        ),
    ),
    'training_clinics' => array(
        array(
            'title'       => 'Route Running Lab',
            'focus'       => 'Stack releases, option stems, and timing windows.',
            'coach'       => 'Coach Alyssa Moore',
            'dates'       => 'Mondays • 7:30 PM • Starburst Park',
            'division'    => 'Pro-Am & Open',
            'cta_label'   => 'Reserve a Spot',
            'cta_url'     => 'https://legendsofthepark.com/clinics/routes',
        ),
        array(
            'title'       => 'Defensive IQ Film Room',
            'focus'       => 'Rotating from two-high looks and disguising blitz packages.',
            'coach'       => 'Defensive Coordinator Malik Evans',
            'dates'       => 'Wednesdays • 8:00 PM • Legends HQ',
            'division'    => 'All Divisions',
            'cta_label'   => 'Download Session Notes',
            'cta_url'     => 'https://legendsofthepark.com/resources/defense-iq.pdf',
        ),
        array(
            'title'       => 'Youth Skills Combine',
            'focus'       => 'Agility ladders, catching fundamentals, and leadership huddles.',
            'coach'       => 'Coach Dani Ortega',
            'dates'       => 'Saturdays • 9:00 AM • Northern Lights Field',
            'division'    => 'Rising Stars',
            'cta_label'   => 'Parent Registration',
            'cta_url'     => 'https://legendsofthepark.com/clinics/youth',
        ),
    ),
    'community_pillars' => array(
        'Inclusive rosters with equal snap counts for every athlete.',
        'Certified trainers at each site with on-call injury support.',
        'Weekly Discord recaps, film cutups, and stat-tracking.',
    ),
    'registration_steps' => array(
        'Create your roster with at least seven players and assign two captains.',
        'Upload waivers and jersey numbers through the membership portal.',
        'Choose a preferred practice slot—league staff confirms within 24 hours.',
        'Join the Discord to coordinate scrimmages and receive scouting packets.',
    ),
    'contact_email' => 'commissioner@legendsofthepark.com',
    'rulebook_url'  => 'https://legendsofthepark.com/resources/flag-football-rulebook.pdf',
    'divisions'     => array(
        'pro-am' => array(
            'name'        => 'Pro-Am Division',
            'tagline'     => 'Elite adult squads combining tournament pedigree with community pride.',
            'description' => 'Designed for top-seeded teams hungry for national qualifiers. Expect pace, precision timing, and defensive schemes built on pressure packages.',
            'image'       => 'https://images.unsplash.com/photo-1518600005860-6defb67639a7?auto=format&fit=crop&w=1200&q=80',
            'image_alt'   => 'Receiver extending for a catch under stadium lights.',
            'home_field'  => 'Starburst Park Stadium — Las Vegas, NV',
            'map_embed'   => 'https://maps.google.com/maps?q=Starburst+Park+Las+Vegas+NV&output=embed',
            'features'    => array(
                '40-second play clock & no-blitz zones at midfield',
                'Live-streamed primetime slots every Thursday',
                'Performance data captured with Catapult trackers',
            ),
            'teams'       => array(
                array(
                    'name'       => 'Sunset Strikers',
                    'record'     => '5-0',
                    'coach'      => 'Alyssa Moore',
                    'captains'   => 'Jordan Price & Malik Evans',
                    'identity'   => 'Tempo offense stretching the field with layered route concepts.',
                    'strengths'  => array('No-huddle mastery', 'Hybrid man-match coverage', 'Deep receiving corps'),
                    'next_match' => 'vs. Neon Knights — July 12',
                    'training'   => 'Tuesdays & Thursdays • 7 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/sunset-strikers',
                ),
                array(
                    'name'       => 'Neon Knights',
                    'record'     => '4-1',
                    'coach'      => 'Chris Delgado',
                    'captains'   => 'Renee Collins & Zion Tate',
                    'identity'   => 'Attack defenses with empty backfield sets and double moves.',
                    'strengths'  => array('Creative motion packages', 'Aggressive blitz disguises', 'Two-way athletes'),
                    'next_match' => 'at Sunset Strikers — July 12',
                    'training'   => 'Mondays • 8 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/neon-knights',
                ),
                array(
                    'name'       => 'Mirage Monarchs',
                    'record'     => '3-2',
                    'coach'      => 'Taylor Kim',
                    'captains'   => 'Devon Hart & Saria Patel',
                    'identity'   => 'RPO-inspired looks with rhythm passing and opportunistic defense.',
                    'strengths'  => array('Third-down efficiency', 'Ball-hawking safeties', 'Red-zone creativity'),
                    'next_match' => 'vs. Las Vegas Legends — July 19',
                    'training'   => 'Wednesdays • 7 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/mirage-monarchs',
                ),
                array(
                    'name'       => 'Las Vegas Legends',
                    'record'     => '2-3',
                    'coach'      => 'Morgan Ellis',
                    'captains'   => 'Andre Watts & Priya Desai',
                    'identity'   => 'Veteran roster leaning on timing-based west coast concepts.',
                    'strengths'  => array('Disciplined route trees', 'Low penalty rate', 'Clutch fourth-down stops'),
                    'next_match' => 'at Mirage Monarchs — July 19',
                    'training'   => 'Fridays • 6 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/las-vegas-legends',
                ),
                array(
                    'name'       => 'Silver Blitz',
                    'record'     => '1-4',
                    'coach'      => 'Gabe Ramirez',
                    'captains'   => 'Elena Brooks & Mateo King',
                    'identity'   => 'Physical press coverage paired with quick-hit mesh concepts.',
                    'strengths'  => array('Press corner tandem', 'Creative goal-line plays', 'Special teams spark'),
                    'next_match' => 'vs. Neon Knights — July 26',
                    'training'   => 'Tuesdays • 8 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/silver-blitz',
                ),
            ),
        ),
        'open' => array(
            'name'        => 'Open Division',
            'tagline'     => 'Co-ed community league mixing newcomers and veteran playmakers.',
            'description' => 'The Open Division keeps things high energy with creative playbooks, rotating QB committees, and halftime fan competitions.',
            'image'       => 'https://images.unsplash.com/photo-1521412644187-c49fa049e84d?auto=format&fit=crop&w=1200&q=80',
            'image_alt'   => 'Flag football players celebrating a touchdown.',
            'home_field'  => 'Heritage Gridiron Complex — Henderson, NV',
            'map_embed'   => 'https://maps.google.com/maps?q=Heritage+Park+Henderson+NV&output=embed',
            'features'    => array(
                'Coaching mentors assigned to every first-year captain',
                'Live stats booth publishing Discord recaps nightly',
                'Rotating DJs and food trucks on Saturday slates',
            ),
            'teams'       => array(
                array(
                    'name'       => 'Silver State Cyclones',
                    'record'     => '4-0-1',
                    'coach'      => 'Imani Rivers',
                    'captains'   => 'Casey Liu & Harper James',
                    'identity'   => 'Spread concepts with roll-out quarterbacks and layered crossing routes.',
                    'strengths'  => array('Motion-heavy offense', 'Hands team on special plays', 'Positive turnover margin'),
                    'next_match' => 'vs. Desert Vipers — July 13',
                    'training'   => 'Thursdays • 6:30 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/cyclones',
                ),
                array(
                    'name'       => 'Desert Vipers',
                    'record'     => '3-1-1',
                    'coach'      => 'Jonas Farley',
                    'captains'   => 'Lena Ortiz & Jalen McCoy',
                    'identity'   => 'Defensive-minded with disguised zones and opportunistic pick plays.',
                    'strengths'  => array('Disciplined safeties', 'Balanced run-pass ratio', 'Sideline communication'),
                    'next_match' => 'at Silver State Cyclones — July 13',
                    'training'   => 'Tuesdays • 7 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/desert-vipers',
                ),
                array(
                    'name'       => 'Valley Comets',
                    'record'     => '3-2',
                    'coach'      => 'Rochelle Carter',
                    'captains'   => 'Evan Rhodes & Tasha Ng',
                    'identity'   => 'Option concepts blended with quick-hitting screens to space playmakers.',
                    'strengths'  => array('Yards after catch', 'Adaptive coverage drops', 'Two-minute drill execution'),
                    'next_match' => 'vs. Mojave Mavericks — July 20',
                    'training'   => 'Wednesdays • 6 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/valley-comets',
                ),
                array(
                    'name'       => 'Mojave Mavericks',
                    'record'     => '2-3',
                    'coach'      => 'Parker Sloan',
                    'captains'   => 'Lindsey Hall & Marco Vega',
                    'identity'   => 'High-morale roster leaning on creative trick plays and lateral concepts.',
                    'strengths'  => array('Sideline culture', 'After-catch creativity', 'Situational blitz timing'),
                    'next_match' => 'at Valley Comets — July 20',
                    'training'   => 'Mondays • 6 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/mojave-mavericks',
                ),
                array(
                    'name'       => 'Cactus Reign',
                    'record'     => '1-4',
                    'coach'      => 'Shea Delgado',
                    'captains'   => 'Maya Brooks & Oliver Trent',
                    'identity'   => 'Grinding drives and clock control built on possession offense.',
                    'strengths'  => array('Clock management', 'Physical flag pulls', 'Specialty screen game'),
                    'next_match' => 'vs. Desert Vipers — July 27',
                    'training'   => 'Fridays • 6 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/cactus-reign',
                ),
            ),
        ),
        'womens-elevate' => array(
            'name'        => 'Women’s Elevate Division',
            'tagline'     => 'Premier women-led squads redefining flag football strategy.',
            'description' => 'Elevate is a fully women-run competition slate with specialized clinics, mentorship pairings, and leadership summits every month.',
            'image'       => 'https://images.unsplash.com/photo-1611848266537-3e994e512f2c?auto=format&fit=crop&w=1200&q=80',
            'image_alt'   => 'A quarterback leading a flag football huddle.',
            'home_field'  => 'Legends Practice Fields — North Las Vegas, NV',
            'map_embed'   => 'https://maps.google.com/maps?q=Craig+Ranch+Regional+Park+North+Las+Vegas&output=embed',
            'features'    => array(
                'Leadership council and monthly mentorship roundtables',
                'On-site childcare and youth flag scrimmages',
                'Full-game film breakdowns with national coaches',
            ),
            'teams'       => array(
                array(
                    'name'       => 'Wildflower Warriors',
                    'record'     => '4-1',
                    'coach'      => 'Dani Ortega',
                    'captains'   => 'Keisha Holt & Amber Lopez',
                    'identity'   => 'Zone-match defense feeding a creative bunch screen offense.',
                    'strengths'  => array('Ball skills', 'Red-zone stops', 'Positive turnover ratio'),
                    'next_match' => 'vs. Mojave Mermaids — July 18',
                    'training'   => 'Tuesdays • 6 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/wildflower-warriors',
                ),
                array(
                    'name'       => 'Mojave Mermaids',
                    'record'     => '4-1',
                    'coach'      => 'Riley Summers',
                    'captains'   => 'Noelle Carter & Aspen Tran',
                    'identity'   => 'Spread principles with dual-quarterback looks and tempo shifts.',
                    'strengths'  => array('Tempo control', 'Stacked blitz packages', 'Dynamic slot receivers'),
                    'next_match' => 'at Wildflower Warriors — July 18',
                    'training'   => 'Thursdays • 7 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/mojave-mermaids',
                ),
                array(
                    'name'       => 'Sierra Sirens',
                    'record'     => '3-2',
                    'coach'      => 'Naomi Brooks',
                    'captains'   => 'Jade Fox & Taryn Lee',
                    'identity'   => 'Balanced offense anchored by unselfish route combinations.',
                    'strengths'  => array('Disciplined pursuit angles', 'Cadence variation', 'High completion percentage'),
                    'next_match' => 'vs. Neon Valkyries — July 25',
                    'training'   => 'Mondays • 7 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/sierra-sirens',
                ),
                array(
                    'name'       => 'Neon Valkyries',
                    'record'     => '2-3',
                    'coach'      => 'Sydney Harper',
                    'captains'   => 'Mika Shaw & Erin Patel',
                    'identity'   => 'Aerial attack that stresses seams with double stacks and back-shoulder fades.',
                    'strengths'  => array('Vertical passing threats', 'Sideline communication', 'Smart blitz adjustments'),
                    'next_match' => 'at Sierra Sirens — July 25',
                    'training'   => 'Wednesdays • 7 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/neon-valkyries',
                ),
                array(
                    'name'       => 'Vegas Phoenix',
                    'record'     => '1-4',
                    'coach'      => 'Amelia Cruz',
                    'captains'   => 'Jolie Martinez & Kendall Price',
                    'identity'   => 'Relentless hustle team anchored by blitz-heavy defensive fronts.',
                    'strengths'  => array('Swarming defense', 'Special teams hustle', 'Locker room culture'),
                    'next_match' => 'vs. Mojave Mermaids — July 27',
                    'training'   => 'Fridays • 6 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/vegas-phoenix',
                ),
            ),
        ),
        'rising-stars' => array(
            'name'        => 'Rising Stars Division',
            'tagline'     => 'Youth flag football pipeline guiding athletes ages 9-14.',
            'description' => 'Legends coaches invest in fundamentals, confidence, and leadership through rotational coaching staffs and chalk talk before every game.',
            'image'       => 'https://images.unsplash.com/photo-1547347298-4074fc3086f0?auto=format&fit=crop&w=1200&q=80',
            'image_alt'   => 'Youth flag football players running drills at sunset.',
            'home_field'  => 'Northern Lights Athletic Field — Sparks, NV',
            'map_embed'   => 'https://maps.google.com/maps?q=Northern+Lights+Park+Sparks+NV&output=embed',
            'features'    => array(
                'Certified youth coaches with SafeSport training',
                'Parents huddles covering nutrition and rest routines',
                'Quarterly combine testing to track growth',
            ),
            'teams'       => array(
                array(
                    'name'       => 'Future Flyers',
                    'record'     => '4-0-1',
                    'coach'      => 'Coach Damon Lee',
                    'captains'   => 'Maya Chen & Isaiah Ward',
                    'identity'   => 'Up-tempo offense teaching pre-snap reads and checkdowns.',
                    'strengths'  => array('Quick decision-making', 'Flag pulling fundamentals', 'Supportive sideline energy'),
                    'next_match' => 'vs. Sparks Falcons — July 20',
                    'training'   => 'Mondays & Wednesdays • 5 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/future-flyers',
                ),
                array(
                    'name'       => 'Sparks Falcons',
                    'record'     => '3-1-1',
                    'coach'      => 'Coach Aisha Grant',
                    'captains'   => 'Luca Ramirez & Zoe Hart',
                    'identity'   => 'Ball-control schemes with emphasis on route spacing.',
                    'strengths'  => array('Team communication', 'Turnover margin', 'Balanced playbook'),
                    'next_match' => 'at Future Flyers — July 20',
                    'training'   => 'Tuesdays • 5:30 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/sparks-falcons',
                ),
                array(
                    'name'       => 'Meadow Mustangs',
                    'record'     => '3-2',
                    'coach'      => 'Coach Leo Hernandez',
                    'captains'   => 'Carmen Diaz & Parker Wells',
                    'identity'   => 'Mix of zone and man concepts to teach versatility.',
                    'strengths'  => array('Adaptable defense', 'Team-first culture', 'High motor effort'),
                    'next_match' => 'vs. Desert Dash — July 27',
                    'training'   => 'Thursdays • 5 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/meadow-mustangs',
                ),
                array(
                    'name'       => 'Desert Dash',
                    'record'     => '2-3',
                    'coach'      => 'Coach Priya Singh',
                    'captains'   => 'Noah Ellis & Ruby Coleman',
                    'identity'   => 'Focus on misdirection plays and speed-in-space concepts.',
                    'strengths'  => array('Jet motion', 'Positive attitudes', 'Creative play calls'),
                    'next_match' => 'at Meadow Mustangs — July 27',
                    'training'   => 'Fridays • 5 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/desert-dash',
                ),
                array(
                    'name'       => 'Canyon Cougars',
                    'record'     => '1-4',
                    'coach'      => 'Coach Nina Alvarez',
                    'captains'   => 'Eli Brooks & Stella King',
                    'identity'   => 'Defense-first team teaching leverage, pursuit, and teamwork.',
                    'strengths'  => array('Fundamental tackling angles', 'Encouraging leadership', 'Progress tracking charts'),
                    'next_match' => 'vs. Sparks Falcons — August 3',
                    'training'   => 'Wednesdays • 5 PM',
                    'scouting'   => 'https://legendsofthepark.com/scouting/canyon-cougars',
                ),
            ),
        ),
    ),
);
