<?php
/**
 * Static dataset describing Nevada park divisions and parks.
 *
 * @package Legends_Of_The_Park
 */

return array(
    'las-vegas' => array(
        'name'        => 'Las Vegas Division',
        'tagline'     => 'Desert sunsets, community runs, and year-round recreation.',
        'description' => 'From Summerlin to Sunrise Manor, the Las Vegas division mixes lush green spaces with skyline views. Evening strolls, weekend leagues, and family festivals make these parks a nightly tradition for locals.',
        'image'       => 'https://images.unsplash.com/photo-1470246973918-29a93221c455?auto=format&fit=crop&w=1200&q=80',
        'image_alt'   => 'The Las Vegas skyline glowing behind palm trees at sunset.',
        'map_embed'   => 'https://maps.google.com/maps?q=Las+Vegas+NV+parks&output=embed',
        'features'    => array(
            'Five signature city parks',
            'Night-lit courts and league play',
            'Cooling splash pads and skate plazas',
        ),
        'parks'       => array(
            array(
                'name'        => 'Desert Breeze Park',
                'location'    => '8275 Spring Mountain Rd, Las Vegas, NV',
                'description' => 'A west-side oasis with shady loops, a fitness course, and a lively weekend farmer’s market under the desert sky.',
                'amenities'   => array('Trails & fitness loops', 'Splash pad & playground', 'Skate park', 'Soccer complex'),
                'image'       => 'https://images.unsplash.com/photo-1533000971552-6a962ff0b9ef?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Joggers on a tree-lined path at sunset.',
                'map_embed'   => 'https://maps.google.com/maps?q=Desert+Breeze+Park+Las+Vegas+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Desert+Breeze+Park+Las+Vegas,+NV',
            ),
            array(
                'name'        => 'Lorenzi Park',
                'location'    => '3333 W Washington Ave, Las Vegas, NV',
                'description' => 'Built around a twinkling urban lake, Lorenzi is the go-to for paddle boating, picnic reunions, and community concerts.',
                'amenities'   => array('Lake loop & fishing pier', 'Festival lawns', 'Historic rose garden'),
                'image'       => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Still water reflecting palm trees and a colorful sky.',
                'map_embed'   => 'https://maps.google.com/maps?q=Lorenzi+Park+Las+Vegas+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Lorenzi+Park+Las+Vegas,+NV',
            ),
            array(
                'name'        => 'Sunset Park',
                'location'    => '2601 E Sunset Rd, Las Vegas, NV',
                'description' => 'One of the valley’s largest parks featuring disc golf, sand volleyball, and a desert lagoon perfect for sunrise fishing.',
                'amenities'   => array('Disc golf course', 'Sand volleyball', 'Fishing lagoon', 'Dune boardwalk'),
                'image'       => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Morning light over a tranquil desert lagoon.',
                'map_embed'   => 'https://maps.google.com/maps?q=Sunset+Park+Las+Vegas+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Sunset+Park+Las+Vegas,+NV',
            ),
            array(
                'name'        => 'Mullins Park',
                'location'    => '5800 E Washburn Rd, Las Vegas, NV',
                'description' => 'Neighborhood ballfields framed by mountain views with batting cages, open lawns, and nightly pickup games.',
                'amenities'   => array('Lighted baseball diamonds', 'Open green space', 'Playground pavilion'),
                'image'       => 'https://images.unsplash.com/photo-1523419409543-0c1df022bdd1?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Baseball diamond lights turning on at dusk.',
                'map_embed'   => 'https://maps.google.com/maps?q=Mullins+Park+Las+Vegas+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Mullins+Park+Las+Vegas,+NV',
            ),
            array(
                'name'        => 'Pavilion Center Park',
                'location'    => '101 S Pavilion Center Dr, Las Vegas, NV',
                'description' => 'Summerlin’s sleek civic hub with artful landscaping, bocce courts, and a family lawn beside the public library.',
                'amenities'   => array('Walking promenade', 'Bocce & basketball', 'Community lawn'),
                'image'       => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Palm-lined promenade with modern civic buildings.',
                'map_embed'   => 'https://maps.google.com/maps?q=Pavilion+Center+Park+Las+Vegas+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Pavilion+Center+Park+Las+Vegas,+NV',
            ),
        ),
    ),
    'henderson' => array(
        'name'        => 'Henderson Division',
        'tagline'     => 'Neighborhood pride, desert vistas, and family-focused amenities.',
        'description' => 'South of Las Vegas, Henderson’s parks weave through master-planned trails, botanical gardens, and hillside overlooks, offering calm morning walks and active evening leagues.',
        'image'       => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
        'image_alt'   => 'Henderson city trails weaving through desert hills.',
        'map_embed'   => 'https://maps.google.com/maps?q=Henderson+NV+parks&output=embed',
        'features'    => array(
            'Desert botanical gardens & nature play',
            'Connected trail network across neighborhoods',
            'Community centers with indoor fitness',
        ),
        'parks'       => array(
            array(
                'name'        => 'Acacia Park',
                'location'    => '50 Casa Del Fuego St, Henderson, NV',
                'description' => 'Botanical pathways surround splash features, shaded lawns, and the Henderson Bird Viewing Preserve trailhead.',
                'amenities'   => array('Botanical garden displays', 'Interactive splash area', 'Adventure playground'),
                'image'       => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Colorful xeriscape garden with walking path.',
                'map_embed'   => 'https://maps.google.com/maps?q=Acacia+Park+Henderson+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Acacia+Park+Henderson,+NV',
            ),
            array(
                'name'        => 'Anthem Hills Park',
                'location'    => '2256 N Reunion Dr, Henderson, NV',
                'description' => 'Perched above the valley, Anthem Hills boasts sweeping views, challenging bike trails, and a beloved skate plaza.',
                'amenities'   => array('Scenic overlook trails', 'Skate park', 'Baseball complex', 'Dog park'),
                'image'       => 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Cyclist climbing a desert ridge at sunrise.',
                'map_embed'   => 'https://maps.google.com/maps?q=Anthem+Hills+Park+Henderson+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Anthem+Hills+Park+Henderson,+NV',
            ),
            array(
                'name'        => 'Cornerstone Park',
                'location'    => '1600 Wigwam Pkwy, Henderson, NV',
                'description' => 'Centered on a shimmering lake, Cornerstone features a half-mile boardwalk loop, fitness stations, and frequent sunset yoga.',
                'amenities'   => array('Lakeside boardwalk', 'Fitness stations', 'Kayak launches'),
                'image'       => 'https://images.unsplash.com/photo-1523419409543-0c1df022bdd1?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Boardwalk curving around a tranquil lake.',
                'map_embed'   => 'https://maps.google.com/maps?q=Cornerstone+Park+Henderson+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Cornerstone+Park+Henderson,+NV',
            ),
            array(
                'name'        => 'Mission Hills Park',
                'location'    => '551 E Mission Dr, Henderson, NV',
                'description' => 'A hillside complex with tennis, baseball, and tree-shaded picnic groves that look back toward the Strip skyline.',
                'amenities'   => array('Baseball complex', 'Tennis courts', 'Shaded picnic grove'),
                'image'       => 'https://images.unsplash.com/photo-1523419409543-0c1df022bdd1?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Families gathering under shade structures in a park.',
                'map_embed'   => 'https://maps.google.com/maps?q=Mission+Hills+Park+Henderson+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Mission+Hills+Park+Henderson,+NV',
            ),
            array(
                'name'        => 'Whitney Ranch Recreation Center',
                'location'    => '1575 Galleria Dr, Henderson, NV',
                'description' => 'An indoor-outdoor destination with aquatic programs, fitness classes, and play lawns linked to the Pittman Wash Trail.',
                'amenities'   => array('Indoor aquatics center', 'Fitness classes', 'Trail connector'),
                'image'       => 'https://images.unsplash.com/photo-1523419409543-0c1df022bdd1?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Modern recreation center beside palm trees.',
                'map_embed'   => 'https://maps.google.com/maps?q=Whitney+Ranch+Recreation+Center+Henderson+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Whitney+Ranch+Recreation+Center+Henderson,+NV',
            ),
        ),
    ),
    'reno' => array(
        'name'        => 'Reno Division',
        'tagline'     => 'Riverfront paths, alpine air, and artful community spaces.',
        'description' => 'Reno’s parks hug the Truckee River and the foothills of the Sierra Nevada. Expect leafy shade, historic structures, and year-round outdoor culture from concerts to cyclocross.',
        'image'       => 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80',
        'image_alt'   => 'Truckee River flowing through downtown Reno with fall colors.',
        'map_embed'   => 'https://maps.google.com/maps?q=Reno+NV+parks&output=embed',
        'features'    => array(
            'Riverfront festivals and art walks',
            'Four-season playgrounds & sports',
            'Mountain bike and nature trail access',
        ),
        'parks'       => array(
            array(
                'name'        => 'Idlewild Park',
                'location'    => '2055 Idlewild Dr, Reno, NV',
                'description' => 'Historic tree groves line the Truckee River with a rose garden, train rides for kids, and lively summer concerts.',
                'amenities'   => array('Riverfront trail', 'Reno Rose Garden', 'Playgrounds & pool'),
                'image'       => 'https://images.unsplash.com/photo-1530543787849-128d94430c6b?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Riverbank trail under tall shade trees.',
                'map_embed'   => 'https://maps.google.com/maps?q=Idlewild+Park+Reno+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Idlewild+Park+Reno,+NV',
            ),
            array(
                'name'        => 'Rancho San Rafael Regional Park',
                'location'    => '1595 N Sierra St, Reno, NV',
                'description' => 'Reno’s largest regional park featuring the Wilbur D. May Arboretum, desert nature loops, and Great Balloon Race launch fields.',
                'amenities'   => array('Arboretum & botanical gardens', 'Nature trails', 'Event lawns'),
                'image'       => 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Balloon festival at sunrise over park lawns.',
                'map_embed'   => 'https://maps.google.com/maps?q=Rancho+San+Rafael+Regional+Park+Reno+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Rancho+San+Rafael+Regional+Park+Reno,+NV',
            ),
            array(
                'name'        => 'McKinley Park',
                'location'    => '925 Riverside Dr, Reno, NV',
                'description' => 'Just west of downtown, McKinley hosts art events, kayaking clinics, and a riverside amphitheater for night markets.',
                'amenities'   => array('River path & kayak launch', 'Historic community center', 'Outdoor amphitheater'),
                'image'       => 'https://images.unsplash.com/photo-1523419409543-0c1df022bdd1?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'People gathered near a riverside amphitheater.',
                'map_embed'   => 'https://maps.google.com/maps?q=McKinley+Park+Reno+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=McKinley+Park+Reno,+NV',
            ),
            array(
                'name'        => 'Magic Carpet Playground',
                'location'    => '1900 Idlewild Dr, Reno, NV',
                'description' => 'An accessible wonderland with colorful ramps, inclusive swings, and sensory play set under towering cottonwoods.',
                'amenities'   => array('Inclusive playground', 'Picnic lawns', 'Shade structures'),
                'image'       => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Children exploring a colorful inclusive playground.',
                'map_embed'   => 'https://maps.google.com/maps?q=Magic+Carpet+Playground+Reno+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Magic+Carpet+Playground+Reno,+NV',
            ),
            array(
                'name'        => 'Evelyn Mount Northeast Park',
                'location'    => '1200 N Sullivan Ln, Reno, NV',
                'description' => 'A sports complex known for its softball tournaments, fitness loops, and indoor recreation center serving Northeast Reno.',
                'amenities'   => array('Softball & soccer fields', 'Fitness trail', 'Community recreation center'),
                'image'       => 'https://images.unsplash.com/photo-1523419409543-0c1df022bdd1?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Softball players in action under bright lights.',
                'map_embed'   => 'https://maps.google.com/maps?q=Evelyn+Mount+Northeast+Park+Reno+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Evelyn+Mount+Northeast+Park+Reno,+NV',
            ),
        ),
    ),
    'carson-city' => array(
        'name'        => 'Carson City Division',
        'tagline'     => 'Capitol history, riverfront trails, and open alpine skies.',
        'description' => 'Carson City parks pair Nevada’s capital landmarks with wide-open desert foothills. Rail history, archery ranges, and river walks make these spaces a hub for outdoor families.',
        'image'       => 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=80',
        'image_alt'   => 'Golden light over the Carson City foothills.',
        'map_embed'   => 'https://maps.google.com/maps?q=Carson+City+NV+parks&output=embed',
        'features'    => array(
            'Historic railroad heritage',
            'Archery, biking, and open desert views',
            'Shaded picnic groves along the Carson River',
        ),
        'parks'       => array(
            array(
                'name'        => 'Mills Park',
                'location'    => '1111 E William St, Carson City, NV',
                'description' => 'Home to the Nevada State Railroad Museum stop, Mills Park mixes festival lawns, skate plazas, and shaded picnic shelters.',
                'amenities'   => array('Historic train rides', 'Skate & BMX plaza', 'Shaded picnic shelters'),
                'image'       => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Families walking near a historic railroad car.',
                'map_embed'   => 'https://maps.google.com/maps?q=Mills+Park+Carson+City+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Mills+Park+Carson+City,+NV',
            ),
            array(
                'name'        => 'Governor’s Field Park',
                'location'    => '500 E Evalyn Dr, Carson City, NV',
                'description' => 'A competitive baseball hub with tournament-ready fields, batting cages, and a lively concession plaza.',
                'amenities'   => array('Tournament baseball complex', 'Batting cages', 'Playground pavilion'),
                'image'       => 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Baseball field with players warming up at sunset.',
                'map_embed'   => 'https://maps.google.com/maps?q=Governor%27s+Field+Park+Carson+City+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Governor%27s+Field+Park+Carson+City,+NV',
            ),
            array(
                'name'        => 'Centennial Park',
                'location'    => '5400 Heritage Way, Carson City, NV',
                'description' => 'High desert terrain for mountain biking, archery, and panoramic sunrise views across the Eagle Valley.',
                'amenities'   => array('Mountain bike loops', 'Archery range', 'Multi-sport complex'),
                'image'       => 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Mountain biker navigating a desert singletrack.',
                'map_embed'   => 'https://maps.google.com/maps?q=Centennial+Park+Carson+City+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Centennial+Park+Carson+City,+NV',
            ),
            array(
                'name'        => 'Empire Ranch Golf Course Park',
                'location'    => '1875 Fair Way, Carson City, NV',
                'description' => 'A scenic stretch of Carson River greenway with paved walking loops, birding spots, and views of the surrounding golf fairways.',
                'amenities'   => array('Riverfront walking path', 'Birdwatching overlooks', 'Open lawns'),
                'image'       => 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'River winding through a green valley with mountains in the distance.',
                'map_embed'   => 'https://maps.google.com/maps?q=Empire+Ranch+Golf+Course+Park+Carson+City+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Empire+Ranch+Golf+Course+Park+Carson+City,+NV',
            ),
            array(
                'name'        => 'Carson Riverwalk Park',
                'location'    => '501 S Carson St, Carson City, NV',
                'description' => 'Follow the riverfront trail for kayaking put-ins, wildlife viewing, and quiet picnic nooks steps from downtown.',
                'amenities'   => array('Riverwalk trail', 'Kayak launch', 'Wildlife viewing decks'),
                'image'       => 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=80',
                'image_alt'   => 'Kayaker exploring a calm river surrounded by trees.',
                'map_embed'   => 'https://maps.google.com/maps?q=Carson+Riverwalk+Park+Carson+City+NV&output=embed',
                'directions'  => 'https://maps.google.com/?q=Carson+Riverwalk+Park+Carson+City,+NV',
            ),
        ),
    ),
);
